const REMOVE_LOT = 'REMOVE_LOT' as const ;
const UPDATE_LOT = 'UPDATE_LOT' as const ;
const ADD_LOT = 'ADD_LOT' as const ;
const UPLOADED_FILES = 'UPLOADED_FILES' as const ;
const SET_AVAILABILITY_LOT = 'SET_AVAILABILITY_LOT' as const ;
const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS' as const;
const DELIVERED_ORDER = 'DELIVERED_ORDER' as const;

export default {
  REMOVE_LOT,
  UPDATE_LOT,
  ADD_LOT,
  UPLOADED_FILES,
  SET_AVAILABILITY_LOT,
  FETCH_ALL_ORDERS,
  DELIVERED_ORDER
};